# Do modify this file! It was generated by ‘nixos-generate-config’
# but whatever.
{ lib, modulesPath, ... }: {
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "r8169" ];
  boot.kernelModules = [ "r8169" "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.extraModprobeConfig = "options bluetooth disable_ertm=1 ";

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/1e57d40a-db51-43b3-854e-2b5c243299dc";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/66DE-7C3C";
    fsType = "vfat";
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/a966e066-8896-47b4-bc20-c7d01d4cd0ed"; }];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  # Bluetooth
  # https://nixos.wiki/wiki/Bluetooth
  hardware.bluetooth.enable = true;
  # Don't power up the default Bluetooth controller on boot
  hardware.bluetooth.powerOnBoot = false;
}
