name: create template

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes

    # Use cache for speed up!
    - uses: cachix/cachix-action@v10
      with:
        name: nix-community

    - name: build
      run: |
        rm flake.lock
        # if cache isn't configured continue
        cachix use dmadisetti | echo "cache cannot be used"
        nix run ".#_clean"

    - name: deploy
      uses: JamesIves/github-pages-deploy-action@v4.3.0
      with:
        branch: template
        folder: .
