name: tests

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: build
      run: |
        sudo mkdir -p /home/dylan/.dots/nix
        sudo mv nix/spoof /home/dylan/.dots/nix/sensitive
        nix run ".#_clean"
    - name: deploy
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        branch: template
