name: create template

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: "provision home-mananger"
      uses: ./.github/actions/runner
      id: runner
      with:
        cachix-endpoint: "${{ github.repository_owner }}"
        cachix-token: '${{ secrets.CACHIX_TOKEN }}'

    - name: "strip main into template"
      run: |
        rm flake.lock # easy unlock lol
        nix run ".#_clean"

    - name: "deploy"
      uses: JamesIves/github-pages-deploy-action@v4.4.2
      with:
        branch: template
        folder: .
