name: "build isos"

on:
  workflow_dispatch:
  schedule:
    - cron: "30 9 * * 2"

jobs:
  build-live:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: "provision home-mananger"
      uses: ./.github/actions/runner
      id: runner

    - name: "build public iso"
      run: |
        export DOTFILES="$(pwd)"
        nix run ".#live"
      shell: fish {0}

    - name: "provide default iso"
      uses: actions/upload-artifact@v3
      with:
        name: live-iso
        path: result/iso/*.iso

  build-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: "provision home-mananger"
      uses: ./.github/actions/runner
      id: runner

    - name: "build docker runner"
      run: |
        export DOTFILES="$(pwd)"
        dots-docker
        docker tag dots-docker ghcr.io/${{ github.actor }}/dots
      shell: fish {0}

    - name: Log in to the Container registry
      uses: docker/login-action@1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@2
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.actor }}/dots:latest
