name: "build isos"

on:
  push:

jobs:
  build-live:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./runner
    #- run: echo shell  steps.provision.outputs.shell }}
